// Code generated by go-swagger; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/chaitin/chaitin-cli/products/xray/client/vulnerability"
	"github.com/chaitin/chaitin-cli/products/xray/models"

	"github.com/spf13/cobra"

	"github.com/go-openapi/swag"
)

// makeOperationVulnerabilityPostVulnFilterCmd returns a command to handle operation postVulnFilter
func makeOperationVulnerabilityPostVulnFilterCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PostVulnFilter",
		Short: `按条件批量获取漏洞`,
		RunE:  runOperationVulnerabilityPostVulnFilter,
	}

	if err := registerOperationVulnerabilityPostVulnFilterParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationVulnerabilityPostVulnFilter uses cmd flags to call endpoint api
func runOperationVulnerabilityPostVulnFilter(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := vulnerability.NewPostVulnFilterParams()
	if err, _ = retrieveOperationVulnerabilityPostVulnFilterBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {
		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationVulnerabilityPostVulnFilterResult(appCli.Vulnerability.PostVulnFilter(params, nil))
	if err != nil {
		return err
	}

	if !debug {
		fmt.Println(msgStr)
	}

	return nil
}

// registerOperationVulnerabilityPostVulnFilterParamFlags registers all flags needed to fill params
func registerOperationVulnerabilityPostVulnFilterParamFlags(cmd *cobra.Command) error {
	if err := registerOperationVulnerabilityPostVulnFilterBodyParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationVulnerabilityPostVulnFilterBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var flagBodyName string
	if cmdPrefix == "" {
		flagBodyName = "body"
	} else {
		flagBodyName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(flagBodyName, "", `Optional json string for [body]. `)

	// add flags for body
	if err := registerModelFilterVulnBodyFlags(0, "filterVulnBody", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationVulnerabilityPostVulnFilterBodyFlag(m *vulnerability.PostVulnFilterParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		flagBodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		flagBodyValue := models.FilterVulnBody{}
		if err := decodeFilterVulnBody(flagBodyValueStr, &flagBodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.FilterVulnBody: %w", err), false
		}
		m.Body = &flagBodyValue
	}
	flagBodyModel := m.Body
	if swag.IsZero(flagBodyModel) {
		flagBodyModel = &models.FilterVulnBody{}
	}
	err, added := retrieveModelFilterVulnBodyFlags(0, flagBodyModel, "filterVulnBody", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = flagBodyModel
	}

	if dryRun && debug {
		flagBodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(flagBodyValueDebugBytes))
	}

	retAdded = retAdded || added

	return nil, retAdded
}

func decodeFilterVulnBody(raw string, target *models.FilterVulnBody) error {
	allowedFields := map[string]struct{}{
		"asset_group_ids": {}, "asset_info": {}, "asset_type": {},
		"business_system_ids": {}, "categorys": {}, "created_time": {},
		"definiteness": {}, "exposure": {}, "level": {}, "limit": {},
		"location_ids": {}, "network_region_ids": {}, "offset": {},
		"project_full_name": {}, "project_id": {}, "related_task_name": {},
		"status": {}, "tag_ids": {}, "title": {}, "updated_time": {},
		"xprocess_id": {},
	}

	decoder := json.NewDecoder(strings.NewReader(raw))
	var fields map[string]json.RawMessage
	if err := decoder.Decode(&fields); err != nil {
		return err
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		if err == nil {
			return fmt.Errorf("multiple JSON values are not allowed")
		}
		return err
	}
	for name := range fields {
		if _, ok := allowedFields[name]; !ok {
			return fmt.Errorf("unknown field %q", name)
		}
	}
	return json.Unmarshal([]byte(raw), target)
}

// parseOperationVulnerabilityPostVulnFilterResult parses request result and return the string content
func parseOperationVulnerabilityPostVulnFilterResult(resp0 *vulnerability.PostVulnFilterOK, respErr error) (string, error) {
	if respErr != nil {

		// responses
		var iResp0 any = respErr
		eresp0, ok := iResp0.(*vulnerability.PostVulnFilterOK)
		if ok {
			// the error response has a payload
			if !swag.IsZero(eresp0) && !swag.IsZero(eresp0.Payload) {
				msgStr, err := json.Marshal(eresp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}
		return "", respErr
	}

	// success responses
	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}
	return "", nil
}
